### ISSUE TITLE
White background when converting flag to image

### ISSUE THREAD

**Issue by csr** [cruisediary/Flags#10]
Hey there!

It looks like when I try to convert flags into emojis the image has a white background. I think this is due to `UIColor.white.set()` in the `image(size: CGSize) -> UIImage?` method.

Perhaps you may want to look into this and perhaps give us the ability to choose the background color or have a clear background color.

See image for more info. If you want, I can try to change this behavior by submitting a pull request.

![](https://i.imgur.com/j28fIlQ.png)

Thanks!

**Comment by cruisediary** [comment]
@cesaredecal Thank you for your reporting and PR #11 😄

**Comment by csr** [comment]
No problem, generally though, I think it would be best to leave the default color to `clear` instead of `white` (I have tested it on my end it works just fine).
